apiVersion: v1
kind: Service
metadata:
  name: ds-deployment-0
  namespace: ds-deployment  # Added namespace
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: ds-deployment-0
  ports:
    - port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: ds-deployment-1
  namespace: ds-deployment
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: ds-deployment-1
  ports:
    - port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: ds-deployment-2
  namespace: ds-deployment
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: ds-deployment-2
  ports:
    - port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: ds-deployment-3
  namespace: ds-deployment
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: ds-deployment-3
  ports:
    - port: 50051
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-deployment
  namespace: ds-deployment
  labels:
    app: dist-swarm
spec:
  serviceName: "overmind"
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dist-swarm
  template:
    metadata:
      labels:
        app: dist-swarm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: ds-device
          image: tensorflow/tensorflow
          imagePullPolicy: Always
          ports:
            - containerPort: 50051